# Generated by Django 4.1 on 2022-08-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migration',
            name='destination',
            field=models.CharField(max_length=100),
        ),
    ]
