# Generated by Django 4.1 on 2022-08-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='swallow',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
